/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practica2;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author joz
 */
public class Circulocuadros extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form circulo
     */
    
    private static final int CANT_FILAS = 5;
    private static final int CANT_COLUMNAS = 6;
    private static final int CANT_CIRCULOS = CANT_FILAS * CANT_COLUMNAS;
    private static final int DIAMETRO_CIRCULO = 30;
    private static final int MARGEN_HORIZONTAL = 50;
    private static final int MARGEN_VERTICAL = 50;
    private static final int ESPACIO_ENTRE_CIRCULOS = 10;
    private static final int TIEMPO_ENTRE_CIRCULOS = 1000;
    
    private Color color;
    private int[] posicionesX = new int[CANT_CIRCULOS];
    private int[] posicionesY = new int[CANT_CIRCULOS];
    private int circulosDibujados = 0;
    private boolean enEjecucion = true;
    private boolean desaparecer = false;
    
    
   Thread hilo;
    public Circulocuadros() {
       for (int i = 0; i < CANT_CIRCULOS; i++) {
            int fila = i / CANT_COLUMNAS;
            int columna = i % CANT_COLUMNAS;
            posicionesX[i] = MARGEN_HORIZONTAL + columna * (DIAMETRO_CIRCULO + ESPACIO_ENTRE_CIRCULOS);
            posicionesY[i] = MARGEN_VERTICAL + fila * (DIAMETRO_CIRCULO + ESPACIO_ENTRE_CIRCULOS);
    }
       hilo = new Thread(this);
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void paint(Graphics g){
             super.paintComponent(g);
        if(desaparecer){
        
            for (int i = 0; i < CANT_CIRCULOS - circulosDibujados; i++) {
            g.setColor(color);
            g.fillOval(posicionesX[i], posicionesY[i], DIAMETRO_CIRCULO, DIAMETRO_CIRCULO);
           
        }
        }
   
        else{
         for (int i = 0; i < circulosDibujados; i++) {
            g.setColor(color);
            g.fillOval(posicionesX[i], posicionesY[i], DIAMETRO_CIRCULO, DIAMETRO_CIRCULO);
        
        }   
            
       
        }
        
        
    }
    
    
    public void continuar(){
      hilo.resume();
     
    }
    
    public void inicio(){
      hilo.start();
     
    }
    
    public void pausa() {
        hilo.suspend();
    }
    
    @Override
    public void run() {
        
       while (enEjecucion) {
            try {
                Thread.sleep(TIEMPO_ENTRE_CIRCULOS);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            circulosDibujados++;
            repaint();
            if (circulosDibujados == CANT_CIRCULOS) {
                circulosDibujados = 0;
                desaparecer = true;
            }
        }
    }

   public void setColor(Color color) {
        this.color = color;
    }
//
//   public void setdireccion( int izquierda){
//   
//   this.izquierda=izquierda;
//
//   }
//
//    public void setC(int c) {
//        this.c = c;
//    }
//   
//   
//   
//   public void setCant(int cant){
//   this.cant=cant;
//   }
//   
//   public void SetVelocidad(int vel){
//   this.vel=vel;
//   }
//
//    public int getContador() {
//        return contador;
//    }
//
//    public void setCuadro(boolean cuadro) {
//        this.cuadro = cuadro;
//    }
   
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
