/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.AttributedCharacterIterator;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.TimerTask;
import javax.swing.Timer;

/**
 *
 * @author joz
 */
public class simulacion extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form simulacion
     */
    
    tiempos tim = new tiempos(0, 0,0);
    tiempos tinv = new tiempos(0, 0,0);
    tiempos tpro = new tiempos(0, 0,0);
    tiempos tem = new tiempos(0, 0,0);
    tiempos tsa = new tiempos(0, 0,0);
    
    Thread reloj = new Thread(tim);
    Thread reloj1 = new Thread(tinv);
    Thread reloj2  = new Thread(tpro);
    Thread reloj3 = new Thread(tem);
    Thread reloj4 = new Thread(tsa);
    private boolean actT,act,act2,act3,act4;
    private boolean iniciopro, inicioem, iniciosa;
    int icant, pcant, ecant, scant;
    String i,p,e,s;
    
    Timer timer, timer2, timer3 ;
   
    
    public simulacion(String i, String p, String e, String s, int icant, int pcant, int ecant, int scant) {
        
        
        this.i=i;
        this.p=p;
        this.e=e;
        this.s=s;
        this.icant = icant;
        this.pcant = pcant;
        this.ecant = ecant;
        this.scant = scant;
        
        initComponents();
        
        
         
    }

 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Inicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        EmpaCont = new javax.swing.JLabel();
        Tempaquetado = new javax.swing.JLabel();
        circuloempaquetado = new practica2.Circulocuadros();
        jButton2 = new javax.swing.JButton();
        tiem = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ProduccionCont = new javax.swing.JLabel();
        Tproduccion = new javax.swing.JLabel();
        Circuloproduccion = new practica2.Circulocuadros();
        finsalida = new practica2.Circulo();
        jPanel3 = new javax.swing.JPanel();
        SalidaCont = new javax.swing.JLabel();
        Tsalida = new javax.swing.JLabel();
        circulosalida = new practica2.Circulocuadros();
        jPanel4 = new javax.swing.JPanel();
        InventarioCont = new javax.swing.JLabel();
        Tinventario = new javax.swing.JLabel();
        Circuloinventario = new practica2.Circulocuadros();
        inicio = new practica2.Circulo();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mov2 = new practica2.mov();
        canvas1 = new java.awt.Canvas();
        mov3 = new practica2.mov3();
        mov4 = new practica2.mov4();

        jLabel7.setText("00:00:00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        EmpaCont.setText("00");

        Tempaquetado.setText("00:00:00");

        javax.swing.GroupLayout circuloempaquetadoLayout = new javax.swing.GroupLayout(circuloempaquetado);
        circuloempaquetado.setLayout(circuloempaquetadoLayout);
        circuloempaquetadoLayout.setHorizontalGroup(
            circuloempaquetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        circuloempaquetadoLayout.setVerticalGroup(
            circuloempaquetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Tempaquetado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(EmpaCont)
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(circuloempaquetado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tempaquetado)
                    .addComponent(EmpaCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circuloempaquetado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("Regresar");

        tiem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tiem.setText("00:00:00");

        jButton3.setText("Reporte");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentResized(evt);
            }
        });

        ProduccionCont.setText("00");
        ProduccionCont.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ProduccionContInputMethodTextChanged(evt);
            }
        });

        Tproduccion.setText("00:00:00");

        javax.swing.GroupLayout CirculoproduccionLayout = new javax.swing.GroupLayout(Circuloproduccion);
        Circuloproduccion.setLayout(CirculoproduccionLayout);
        CirculoproduccionLayout.setHorizontalGroup(
            CirculoproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        CirculoproduccionLayout.setVerticalGroup(
            CirculoproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Circuloproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Tproduccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(ProduccionCont)
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tproduccion)
                    .addComponent(ProduccionCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Circuloproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout finsalidaLayout = new javax.swing.GroupLayout(finsalida);
        finsalida.setLayout(finsalidaLayout);
        finsalidaLayout.setHorizontalGroup(
            finsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        finsalidaLayout.setVerticalGroup(
            finsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalidaCont.setText("00");

        Tsalida.setText("00:00:00");

        javax.swing.GroupLayout circulosalidaLayout = new javax.swing.GroupLayout(circulosalida);
        circulosalida.setLayout(circulosalidaLayout);
        circulosalidaLayout.setHorizontalGroup(
            circulosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        circulosalidaLayout.setVerticalGroup(
            circulosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Tsalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(SalidaCont)
                .addGap(129, 129, 129))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(circulosalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tsalida)
                    .addComponent(SalidaCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circulosalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel4ComponentAdded(evt);
            }
        });

        InventarioCont.setText("00");
        InventarioCont.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                InventarioContComponentHidden(evt);
            }
        });

        Tinventario.setText("00:00:00");
        Tinventario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TinventarioInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout CirculoinventarioLayout = new javax.swing.GroupLayout(Circuloinventario);
        Circuloinventario.setLayout(CirculoinventarioLayout);
        CirculoinventarioLayout.setHorizontalGroup(
            CirculoinventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        CirculoinventarioLayout.setVerticalGroup(
            CirculoinventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Circuloinventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Tinventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(InventarioCont)
                        .addGap(25, 25, 25))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InventarioCont)
                    .addComponent(Tinventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Circuloinventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Inventario:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Produccion: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Salida: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Empaquetado: ");

        mov2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                mov2ComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                mov2ComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                mov2ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout mov2Layout = new javax.swing.GroupLayout(mov2);
        mov2.setLayout(mov2Layout);
        mov2Layout.setHorizontalGroup(
            mov2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mov2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        mov2Layout.setVerticalGroup(
            mov2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mov2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout mov3Layout = new javax.swing.GroupLayout(mov3);
        mov3.setLayout(mov3Layout);
        mov3Layout.setHorizontalGroup(
            mov3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        mov3Layout.setVerticalGroup(
            mov3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mov4Layout = new javax.swing.GroupLayout(mov4);
        mov4.setLayout(mov4Layout);
        mov4Layout.setHorizontalGroup(
            mov4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mov4Layout.setVerticalGroup(
            mov4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386)
                .addComponent(tiem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(finsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(78, 78, 78)
                                .addComponent(mov4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mov2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(431, 431, 431))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mov3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 117, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(521, 521, 521))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(tiem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addComponent(mov2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mov4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(196, 196, 196))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(mov3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(finsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
       
//        TimerTask tarea = new TimerTask() {
//            @Override
//            public void run() {
//                reloj2.start();
//            }
//        };
        
//        this.timer = new Timer(10000,null);
//         
//         timer.addActionListener(new ActionListener() {
//             @Override
//             public void actionPerformed(ActionEvent e) {
//               reloj2.start();
//               
//             }
//         });
//         timer.start();
//       
//         
//         
//         this.timer2 = new Timer(20000,null);
//          timer2.addActionListener(new ActionListener() {
//             @Override
//             public void actionPerformed(ActionEvent e) {
//               reloj3.start();
//               
//             }
//         });
//         timer2.start();
//         
//         
//         this.timer3 = new Timer(30000,null);
//          timer3.addActionListener(new ActionListener() {
//             @Override
//             public void actionPerformed(ActionEvent e) {
//               reloj4.start();
//               
//             }
//         });
//         timer3.start();
         
         
        
        // Se agrega el cambio recibido en la clase Observable(temporizador)
        tim.addObserver(this);
        tinv.addObserver(this);
        tpro.addObserver(this);
        tem.addObserver(this);
        tsa.addObserver(this);

        
        // Se ejecuta el hilo del temporizador
        reloj.start();
        reloj1.start();
        reloj2.start();
        reloj3.start();
    
        //inicio
        inicio.setC(0);
        inicio.setColor(Color.yellow);
        inicio.setCant(2);
        inicio.setdireccion(100, -50, 0, 0);
        inicio.SetVelocidad(37);
        inicio.inicio();
        
       // st1.inicio();
  
        Circuloinventario.setColor(Color.blue);
        Circuloproduccion.setColor(Color.green);
        circuloempaquetado.setColor(Color.magenta);
        circulosalida.setColor(Color.red);
        
        Circuloinventario.inicio();
       

        //Empaquetado
    
        mov2.setColor(Color.blue);
        mov2.setdireccion(100);
        mov2.inicio();
        mov2.pausa();
        
        mov3.setColor(Color.green);
        mov3.setdireccion(100);
        mov3.inicio();
        mov3.pausa();
        
        
       
       
        
        
        mov4.setColor(Color.magenta);
        mov4.setdireccion(100);
        mov4.inicio();
        mov4.pausa();
        
        //Salida

         
        

        
    }//GEN-LAST:event_InicioActionPerformed

    private void jPanel4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4ComponentAdded

    private void mov2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mov2ComponentShown
        
        
    }//GEN-LAST:event_mov2ComponentShown

    private void jPanel2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentResized
          
        
        
         
    }//GEN-LAST:event_jPanel2ComponentResized

    private void ProduccionContInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ProduccionContInputMethodTextChanged
       
    }//GEN-LAST:event_ProduccionContInputMethodTextChanged

    private void mov2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mov2ComponentResized
 
    }//GEN-LAST:event_mov2ComponentResized

    private void TinventarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TinventarioInputMethodTextChanged

    }//GEN-LAST:event_TinventarioInputMethodTextChanged

    private void mov2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mov2ComponentMoved
        
    }//GEN-LAST:event_mov2ComponentMoved

    private void InventarioContComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_InventarioContComponentHidden

    }//GEN-LAST:event_InventarioContComponentHidden

   
    
    @Override
    public void update(Observable o, Object arg) {
        
        tiem.setText((String) arg);
        
        Tinventario.setText((String) arg);
        Tempaquetado.setText((String) arg);
        Tproduccion.setText((String) arg);
        
        
        InventarioCont.setText(Integer.toString(inicio.getContador()));
        ProduccionCont.setText(Integer.toString(mov2.getContador()));
        EmpaCont.setText(Integer.toString(mov3.getContador()));
        SalidaCont.setText(Integer.toString(mov4.getContador()));
        

        
        if("00:00:31".equals(tiem.getText().toString())){    
        InventarioCont.setVisible(false);
        inicio.setColor(getBackground());
        Circuloinventario.pausa();
        }
        
        
        if(i.equals(tiem.getText().toString())){
        
        Circuloinventario.continuar();
        mov2.continuar();
        mov2.setVisible(true);
        Circuloproduccion.inicio();
        ProduccionCont.setVisible(true);
        }
        
        if("00:00:30".equals(Tproduccion.getText().toString())){    
 
        Circuloproduccion.pausa();
        }
  
        if(p.equals(Tinventario.getText().toString())){
        
        mov3.continuar();
        mov3.setVisible(true);
        Circuloproduccion.continuar();
        circuloempaquetado.inicio();
        
        }
        
        if("00:00:30".equals(Tempaquetado.getText().toString())){    
 
        circuloempaquetado.pausa();
        }
        
        
        if(e.equals(tiem.getText().toString())){
        
        mov4.continuar();
        mov4.setVisible(true);
        circuloempaquetado.continuar();
        circulosalida.inicio();
        
        }
        
        if("00:00:30".equals(Tsalida.getText().toString())){    
 
        circulosalida.pausa();
        }
        
        if(s.equals(tiem.getText().toString())){
        
        circulosalida.continuar();
       
        
        }
       

        }
        
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new simulacion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private practica2.Circulocuadros Circuloinventario;
    private practica2.Circulocuadros Circuloproduccion;
    private javax.swing.JLabel EmpaCont;
    private javax.swing.JButton Inicio;
    private javax.swing.JLabel InventarioCont;
    private javax.swing.JLabel ProduccionCont;
    private javax.swing.JLabel SalidaCont;
    private javax.swing.JLabel Tempaquetado;
    private javax.swing.JLabel Tinventario;
    private javax.swing.JLabel Tproduccion;
    private javax.swing.JLabel Tsalida;
    private java.awt.Canvas canvas1;
    private practica2.Circulocuadros circuloempaquetado;
    private practica2.Circulocuadros circulosalida;
    private practica2.Circulo finsalida;
    private practica2.Circulo inicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private practica2.mov mov2;
    private practica2.mov3 mov3;
    private practica2.mov4 mov4;
    private javax.swing.JLabel tiem;
    // End of variables declaration//GEN-END:variables
}
