/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2;

import java.awt.Color;
import java.awt.Container;
import java.text.AttributedCharacterIterator;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author joz
 */
public class simulacion extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form simulacion
     */
    
    tiempos tim = new tiempos(0, 0,0);
    tiempos tinv = new tiempos(0, 0,0);
    tiempos tpro = new tiempos(0, 0,0);
    tiempos tem = new tiempos(0, 0,0);
    tiempos tsa = new tiempos(0, 0,0);
    
    Thread reloj = new Thread(tim);
    Thread reloj1 = new Thread(tinv);
    Thread reloj2 = new Thread(tpro);
    Thread reloj3 = new Thread(tem);
    Thread reloj4 = new Thread(tsa);
    private boolean actT,act,act2,act3,act4;
    
    String i,p,e,s;
    
    public simulacion(String i, String p, String e, String s) {
        this.i=i;
        this.p=p;
        this.e=e;
        this.s=s;
  
        initComponents();
        vis();
        
         
    }

    public void vis(){
        Inv2.setVisible(false);
        Inv3.setVisible(false);
        Inv4.setVisible(false); 
        Inv5.setVisible(false); 
        Pro1.setVisible(false);
        Pro2.setVisible(false);
        Pro3.setVisible(false);
        Pro4.setVisible(false);
        Pro5.setVisible(false);
        Em1.setVisible(false);
        Em2.setVisible(false);
        Em3.setVisible(false);
        Em4.setVisible(false);
        Em5.setVisible(false);
        Sa1.setVisible(false);
        Sa2.setVisible(false);
        Sa3.setVisible(false);
        Sa4.setVisible(false);
        Sa5.setVisible(false);
        act2 = false;
        act3 = false;
        act4 = false;
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Inicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        EmpaCont = new javax.swing.JLabel();
        Tempaquetado = new javax.swing.JLabel();
        Em1 = new practica2.Circulo();
        Em2 = new practica2.Circulo();
        Em3 = new practica2.Circulo();
        Em4 = new practica2.Circulo();
        Em5 = new practica2.Circulo();
        jButton2 = new javax.swing.JButton();
        tiem = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ProduccionCont = new javax.swing.JLabel();
        Tproduccion = new javax.swing.JLabel();
        Pro1 = new practica2.Circulo();
        Pro2 = new practica2.Circulo();
        Pro3 = new practica2.Circulo();
        Pro4 = new practica2.Circulo();
        Pro5 = new practica2.Circulo();
        finsalida = new practica2.Circulo();
        jPanel3 = new javax.swing.JPanel();
        SalidaCont = new javax.swing.JLabel();
        Tsalida = new javax.swing.JLabel();
        Sa1 = new practica2.Circulo();
        Sa2 = new practica2.Circulo();
        Sa3 = new practica2.Circulo();
        Sa4 = new practica2.Circulo();
        Sa5 = new practica2.Circulo();
        jPanel4 = new javax.swing.JPanel();
        InventarioCont = new javax.swing.JLabel();
        Tinventario = new javax.swing.JLabel();
        Inv1 = new practica2.Circulo();
        Inv2 = new practica2.Circulo();
        Inv3 = new practica2.Circulo();
        Inv4 = new practica2.Circulo();
        Inv5 = new practica2.Circulo();
        inicio = new practica2.Circulo();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mov2 = new practica2.mov();
        canvas1 = new java.awt.Canvas();
        mov3 = new practica2.mov3();
        mov4 = new practica2.mov4();

        jLabel7.setText("00:00:00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        EmpaCont.setText("00");

        Tempaquetado.setText("00:00:00");

        javax.swing.GroupLayout Em1Layout = new javax.swing.GroupLayout(Em1);
        Em1.setLayout(Em1Layout);
        Em1Layout.setHorizontalGroup(
            Em1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Em1Layout.setVerticalGroup(
            Em1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Em2Layout = new javax.swing.GroupLayout(Em2);
        Em2.setLayout(Em2Layout);
        Em2Layout.setHorizontalGroup(
            Em2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Em2Layout.setVerticalGroup(
            Em2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Em3Layout = new javax.swing.GroupLayout(Em3);
        Em3.setLayout(Em3Layout);
        Em3Layout.setHorizontalGroup(
            Em3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Em3Layout.setVerticalGroup(
            Em3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Em4Layout = new javax.swing.GroupLayout(Em4);
        Em4.setLayout(Em4Layout);
        Em4Layout.setHorizontalGroup(
            Em4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Em4Layout.setVerticalGroup(
            Em4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Em5Layout = new javax.swing.GroupLayout(Em5);
        Em5.setLayout(Em5Layout);
        Em5Layout.setHorizontalGroup(
            Em5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Em5Layout.setVerticalGroup(
            Em5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Tempaquetado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(EmpaCont)
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Em1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Em2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Em3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Em4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Em5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tempaquetado)
                    .addComponent(EmpaCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Em1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Em2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Em3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Em4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Em5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton2.setText("Regresar");

        tiem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tiem.setText("00:00:00");

        jButton3.setText("Reporte");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentResized(evt);
            }
        });

        ProduccionCont.setText("00");
        ProduccionCont.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ProduccionContInputMethodTextChanged(evt);
            }
        });

        Tproduccion.setText("00:00:00");

        javax.swing.GroupLayout Pro1Layout = new javax.swing.GroupLayout(Pro1);
        Pro1.setLayout(Pro1Layout);
        Pro1Layout.setHorizontalGroup(
            Pro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        Pro1Layout.setVerticalGroup(
            Pro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Pro2Layout = new javax.swing.GroupLayout(Pro2);
        Pro2.setLayout(Pro2Layout);
        Pro2Layout.setHorizontalGroup(
            Pro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        Pro2Layout.setVerticalGroup(
            Pro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Pro3Layout = new javax.swing.GroupLayout(Pro3);
        Pro3.setLayout(Pro3Layout);
        Pro3Layout.setHorizontalGroup(
            Pro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Pro3Layout.setVerticalGroup(
            Pro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Pro4Layout = new javax.swing.GroupLayout(Pro4);
        Pro4.setLayout(Pro4Layout);
        Pro4Layout.setHorizontalGroup(
            Pro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        Pro4Layout.setVerticalGroup(
            Pro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Pro5Layout = new javax.swing.GroupLayout(Pro5);
        Pro5.setLayout(Pro5Layout);
        Pro5Layout.setHorizontalGroup(
            Pro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Pro5Layout.setVerticalGroup(
            Pro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pro5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Tproduccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProduccionCont)
                        .addGap(34, 34, 34)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tproduccion)
                    .addComponent(ProduccionCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout finsalidaLayout = new javax.swing.GroupLayout(finsalida);
        finsalida.setLayout(finsalidaLayout);
        finsalidaLayout.setHorizontalGroup(
            finsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        finsalidaLayout.setVerticalGroup(
            finsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalidaCont.setText("00");

        Tsalida.setText("00:00:00");

        javax.swing.GroupLayout Sa1Layout = new javax.swing.GroupLayout(Sa1);
        Sa1.setLayout(Sa1Layout);
        Sa1Layout.setHorizontalGroup(
            Sa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Sa1Layout.setVerticalGroup(
            Sa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Sa2Layout = new javax.swing.GroupLayout(Sa2);
        Sa2.setLayout(Sa2Layout);
        Sa2Layout.setHorizontalGroup(
            Sa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Sa2Layout.setVerticalGroup(
            Sa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Sa3Layout = new javax.swing.GroupLayout(Sa3);
        Sa3.setLayout(Sa3Layout);
        Sa3Layout.setHorizontalGroup(
            Sa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Sa3Layout.setVerticalGroup(
            Sa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Sa4Layout = new javax.swing.GroupLayout(Sa4);
        Sa4.setLayout(Sa4Layout);
        Sa4Layout.setHorizontalGroup(
            Sa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Sa4Layout.setVerticalGroup(
            Sa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Sa5Layout = new javax.swing.GroupLayout(Sa5);
        Sa5.setLayout(Sa5Layout);
        Sa5Layout.setHorizontalGroup(
            Sa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Sa5Layout.setVerticalGroup(
            Sa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Tsalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(SalidaCont)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sa5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Sa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tsalida)
                    .addComponent(SalidaCont))
                .addGap(18, 18, 18)
                .addComponent(Sa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel4ComponentAdded(evt);
            }
        });

        InventarioCont.setText("00");

        Tinventario.setText("00:00:00");
        Tinventario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TinventarioInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout Inv1Layout = new javax.swing.GroupLayout(Inv1);
        Inv1.setLayout(Inv1Layout);
        Inv1Layout.setHorizontalGroup(
            Inv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Inv1Layout.setVerticalGroup(
            Inv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Inv2Layout = new javax.swing.GroupLayout(Inv2);
        Inv2.setLayout(Inv2Layout);
        Inv2Layout.setHorizontalGroup(
            Inv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Inv2Layout.setVerticalGroup(
            Inv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Inv3Layout = new javax.swing.GroupLayout(Inv3);
        Inv3.setLayout(Inv3Layout);
        Inv3Layout.setHorizontalGroup(
            Inv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Inv3Layout.setVerticalGroup(
            Inv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Inv4Layout = new javax.swing.GroupLayout(Inv4);
        Inv4.setLayout(Inv4Layout);
        Inv4Layout.setHorizontalGroup(
            Inv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Inv4Layout.setVerticalGroup(
            Inv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Inv5Layout = new javax.swing.GroupLayout(Inv5);
        Inv5.setLayout(Inv5Layout);
        Inv5Layout.setHorizontalGroup(
            Inv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Inv5Layout.setVerticalGroup(
            Inv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Tinventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(InventarioCont)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inv3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Inv4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Inv5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Inv2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Inv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InventarioCont)
                    .addComponent(Tinventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Inventario:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Produccion: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Salida: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Empaquetado: ");

        mov2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                mov2ComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                mov2ComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                mov2ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout mov2Layout = new javax.swing.GroupLayout(mov2);
        mov2.setLayout(mov2Layout);
        mov2Layout.setHorizontalGroup(
            mov2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mov2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        mov2Layout.setVerticalGroup(
            mov2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mov2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout mov3Layout = new javax.swing.GroupLayout(mov3);
        mov3.setLayout(mov3Layout);
        mov3Layout.setHorizontalGroup(
            mov3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        mov3Layout.setVerticalGroup(
            mov3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mov4Layout = new javax.swing.GroupLayout(mov4);
        mov4.setLayout(mov4Layout);
        mov4Layout.setHorizontalGroup(
            mov4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mov4Layout.setVerticalGroup(
            mov4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tiem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338)
                .addComponent(jButton3)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(finsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(78, 78, 78)
                                .addComponent(mov4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mov2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(431, 431, 431))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mov3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 117, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(tiem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addComponent(mov2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mov4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(213, 213, 213))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(mov3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(finsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed

        // Se agrega el cambio resibido en la clase Observable(temporizador)
        tim.addObserver(this);
        tinv.addObserver(this);
        tpro.addObserver(this);
        tem.addObserver(this);
        tsa.addObserver(this);

        // Se ejecuta el hilo del temporizador
        this.act=true;
        reloj.start();
        
        reloj1.start();
        
//        act2 = false;
//        reloj2.start();
//        reloj2.suspend();
        
        act3 = false;
        reloj3.start();
        reloj3.suspend();
        
        act4 = false;
        reloj4.start();
        reloj4.suspend();
        
        //inicio
        inicio.setC(0);
        inicio.setColor(Color.yellow);
        inicio.setCant(2);
        inicio.setdireccion(100, -50, 0, 0);
        inicio.SetVelocidad(37);
        inicio.inicio();
        
       // st1.inicio();
  
        //inventario
        Inv1.setC(100000);
        Inv1.setColor(Color.BLUE);
        Inv1.setCant(7);
        Inv1.setdireccion(0, -100, 0, 0);
        Inv1.SetVelocidad(240);
        Inv1.inicio();
        
        Inv2.setC(100000);
        Inv2.setColor(Color.BLUE);
        Inv2.setCant(7);
        Inv2.setdireccion(0, -100, 0, 0);
        Inv2.SetVelocidad(240);
        Inv2.inicio();
        Inv2.pausa();
        
        
        Inv3.setC(100000);
        Inv3.setColor(Color.BLUE);
        Inv3.setCant(7);
        Inv3.setdireccion(0, -100, 0, 0);
        Inv3.SetVelocidad(240);
        Inv3.inicio();
        Inv3.pausa();
        
        Inv4.setC(100000);
        Inv4.setColor(Color.BLUE);
        Inv4.setCant(7);
        Inv4.setdireccion(0, -100, 0, 0);
        Inv4.SetVelocidad(240);
        Inv4.inicio();
        Inv4.pausa();
        
        Inv5.setC(100000);
        Inv5.setColor(Color.BLUE);
        Inv5.setCant(7);
        Inv5.setdireccion(0, -1000, 0, 0);
        Inv5.SetVelocidad(240);
        Inv5.inicio();
        Inv5.pausa();
        
        //inventario a produccion
        
        mov2.setColor(Color.blue);
        mov2.setdireccion(100);
        mov2.inicio();
        mov2.pausa();
        
        //Produccion
        Pro1.setC(100000);
        Pro1.setColor(Color.GREEN);
        Pro1.setCant(7);
        Pro1.setdireccion(0, -100, 0, 0);
        Pro1.SetVelocidad(240);
        Pro1.inicio();
        Pro1.pausa();
        
        Pro2.setC(100000);
        Pro2.setColor(Color.GREEN);
        Pro2.setCant(7);
        Pro2.setdireccion(0, -100, 0, 0);
        Pro2.SetVelocidad(240);
        Pro2.inicio();
        Pro2.pausa();
        
        
        Pro3.setC(100000);
        Pro3.setColor(Color.GREEN);
        Pro3.setCant(7);
        Pro3.setdireccion(0, -100, 0, 0);
        Pro3.SetVelocidad(240);
        Pro3.inicio();
        Pro3.pausa();
        
        Pro4.setC(100000);
        Pro4.setColor(Color.GREEN);
        Pro4.setCant(7);
        Pro4.setdireccion(0, -100, 0, 0);
        Pro4.SetVelocidad(240);
        Pro4.inicio();
        Pro4.pausa();
        
        Pro5.setC(100000);
        Pro5.setColor(Color.GREEN);
        Pro5.setCant(7);
        Pro5.setdireccion(0, -1000, 0, 0);
        Pro5.SetVelocidad(240);
        Pro5.inicio();
        Pro5.pausa();
        
        
        //Empaquetado
        
        Em1.setC(100000);
        Em1.setColor(Color.MAGENTA);
        Em1.setCant(7);
        Em1.setdireccion(0, -100, 0, 0);
        Em1.SetVelocidad(240);
        Em1.inicio();
        Em1.pausa();
        
        Em2.setC(100000);
        Em2.setColor(Color.MAGENTA);
        Em2.setCant(7);
        Em2.setdireccion(0, -100, 0, 0);
        Em2.SetVelocidad(240);
        Em2.inicio();
        Em2.pausa();
        
        
        
        mov3.setColor(Color.green);
        mov3.setdireccion(100);
        mov3.inicio();
        mov3.pausa();
        
        
        Em3.setC(100000);
        Em3.setColor(Color.MAGENTA);
        Em3.setCant(8);
        Em3.setdireccion(0, -100, 0, 0);
        Em3.SetVelocidad(240);
        Em3.inicio();
        Em3.pausa();
        
        Em4.setC(100000);
        Em4.setColor(Color.MAGENTA);
        Em4.setCant(8);
        Em4.setdireccion(0, -100, 0, 0);
        Em4.SetVelocidad(240);
        Em4.inicio();
        Em4.pausa();
        
        Em5.setC(100000);
        Em5.setColor(Color.MAGENTA);
        Em5.setCant(7);
        Em5.setdireccion(0, -1000, 0, 0);
        Em5.SetVelocidad(240);
        Em5.inicio();
        Em5.pausa();
        
        
        mov4.setColor(Color.magenta);
        mov4.setdireccion(100);
        mov4.inicio();
        mov4.pausa();
        
        //Salida

         Sa1.setC(100000);
        Sa1.setColor(Color.RED);
        Sa1.setCant(7);
        Sa1.setdireccion(0, -100, 0, 0);
        Sa1.SetVelocidad(240);
        Sa1.inicio();
        Sa1.pausa();
        
        Sa2.setC(100000);
        Sa2.setColor(Color.RED);
        Sa2.setCant(7);
        Sa2.setdireccion(0, -100, 0, 0);
        Sa2.SetVelocidad(240);
        Sa2.inicio();
        Sa2.pausa();
        
        
        Sa3.setC(100000);
        Sa3.setColor(Color.RED);
        Sa3.setCant(7);
        Sa3.setdireccion(0, -100, 0, 0);
        Sa3.SetVelocidad(240);
        Sa3.inicio();
        Sa3.pausa();
        
        Sa4.setC(100000);
        Sa4.setColor(Color.RED);
        Sa4.setCant(7);
        Sa4.setdireccion(0, -100, 0, 0);
        Sa4.SetVelocidad(240);
        Sa4.inicio();
        Sa4.pausa();
        
        Sa5.setC(100000);
        Sa5.setColor(Color.RED);
        Sa5.setCant(7);
        Sa5.setdireccion(0, -1000, 0, 0);
        Sa5.SetVelocidad(240);
        Sa5.inicio();
        Sa5.pausa();
        

        
    }//GEN-LAST:event_InicioActionPerformed

    private void jPanel4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4ComponentAdded

    private void mov2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mov2ComponentShown
        
        
    }//GEN-LAST:event_mov2ComponentShown

    private void jPanel2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentResized
            
    }//GEN-LAST:event_jPanel2ComponentResized

    private void ProduccionContInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ProduccionContInputMethodTextChanged
       
    }//GEN-LAST:event_ProduccionContInputMethodTextChanged

    private void mov2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mov2ComponentResized
  
       
    }//GEN-LAST:event_mov2ComponentResized

    private void TinventarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TinventarioInputMethodTextChanged
       super.processInputMethodEvent(evt);
        System.out.println(evt.toString());  
       if(this.i.toString() == evt.toString()) {
        act2 = true;
        reloj2.start(); 
       } else {}
    }//GEN-LAST:event_TinventarioInputMethodTextChanged

    private void mov2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mov2ComponentMoved
        
    }//GEN-LAST:event_mov2ComponentMoved


    
    @Override
    public void update(Observable o, Object arg) {
        
        tiem.setText((String) arg);
        
        
        if(act){
        Tinventario.setText((String) arg);
        }
        
        if(act2){
        Tproduccion.setText((String) arg);
        ProduccionCont.setVisible(true);
        
        }
        
        if(act3){
        EmpaCont.setVisible(true);
        Tempaquetado.setText((String) arg);
        reloj3.resume();
        }
        
        if(act4){
        SalidaCont.setVisible(true);
        reloj4.resume();
        Tsalida.setText((String) arg);
        }
        

        InventarioCont.setText(Integer.toString(inicio.getContador()));
        ProduccionCont.setText(Integer.toString(mov2.getContador()));
        EmpaCont.setText(Integer.toString(mov3.getContador()));
        SalidaCont.setText(Integer.toString(mov4.getContador()));
        
        
        
        if("00:00:30".equals(tiem.getText().toString())){    
        InventarioCont.setVisible(false);
        inicio.setColor(getBackground());
        this.act=false;
        }
        
        //entrada de circulos
        if("6".equals(InventarioCont.getText().toString())){
        Inv1.pausa();
        Inv2.setVisible(true);
        Inv2.continuar();
        
        }
        
        
        
        if("12".equals(InventarioCont.getText().toString())){
        Inv2.pausa();
        Inv3.setVisible(true);
        Inv3.continuar();
        
        }
        
        if("18".equals(InventarioCont.getText().toString())){
        Inv3.pausa();
        Inv4.setVisible(true);
        Inv4.continuar();
        
        }
        
        if("24".equals(InventarioCont.getText().toString())){
        Inv4.pausa();
        Inv5.setVisible(true);
        Inv5.continuar();
        
        }
        
       
        if("30".equals(InventarioCont.getText().toString())){
        Inv5.pausa();
         
        }
        
        
        
       
        
        //salida de circulos 

        if(i.equals(Tinventario.getText().toString())){
        //this.act=false;
        Inv1.continuar();
        mov2.setVisible(true);
        mov2.continuar();
  
        Pro1.setVisible(true);
        Pro1.continuar();//act2= true;
        }
        
        if("1".equals(ProduccionCont.getText().toString())){
        
        
        }
        
        if("6".equals(ProduccionCont.getText().toString())){
        Pro1.pausa();
        Pro2.setVisible(true);
        Pro2.continuar();
        }
        
        if("12".equals(ProduccionCont.getText().toString())){
        Pro2.pausa();
        Pro3.setVisible(true);
        Pro3.continuar();
        }
        
        if("18".equals(ProduccionCont.getText().toString())){
        Pro3.pausa();
        Pro4.setVisible(true);
        Pro4.continuar();
        }
        
        if("24".equals(ProduccionCont.getText().toString())){
        Pro4.pausa();
        Pro5.setVisible(true);
        Pro5.continuar();
        }
        
        if("30".equals(ProduccionCont.getText().toString())){
        Pro5.pausa();
        }
        
        if("17".equals(InventarioCont.getText().toString())){
        
        Inv2.continuar();
        
        }
        
         if("24".equals(InventarioCont.getText().toString())){
        
        Inv3.continuar();
        
        } 
         if("31".equals(InventarioCont.getText().toString())){
        
        Inv4.continuar();
        
        }
         
         if("38".equals(InventarioCont.getText().toString())){
        
        Inv5.continuar();
        mov2.setVisible(false);
        mov2.pausa();
        
        }
         
        if(p.equals(Tproduccion.getText().toString())){
        //this.act=false;
        this.act2= true;
        this.act3= true;
        Pro1.continuar();
        mov3.setVisible(true);
        mov3.continuar();
        
        }
        
        if("17".equals(ProduccionCont.getText().toString())){
        
        Pro2.continuar();
        
        }
        
         if("24".equals(ProduccionCont.getText().toString())){
        
        Pro3.continuar();
        
        } 
         if("31".equals(ProduccionCont.getText().toString())){
        
        Pro4.continuar();
        
        }
         
         if("38".equals(ProduccionCont.getText().toString())){
        
        Pro5.continuar();
        mov3.setVisible(false);
        mov3.pausa();
        
        }
        
        
        if(e.equals(Tproduccion.getText().toString())){
        //this.act=false;
        
        this.act4= true;
        mov4.setVisible(true);
        mov4.continuar();
        Em1.setVisible(true);
        Em1.continuar();
        }
        
        
         
    if("6".equals(EmpaCont.getText().toString())){
        Em1.pausa();
        Em2.setVisible(true);
        Em2.continuar();
        }
        
        if("12".equals(EmpaCont.getText().toString())){
        Em2.pausa();
        Em3.setVisible(true);
        Em3.continuar();
        }
        
        if("18".equals(EmpaCont.getText().toString())){
        Em3.pausa();
        Em4.setVisible(true);
        Em4.continuar();
        }
        
        if("24".equals(EmpaCont.getText().toString())){
        Em4.pausa();
        Em5.setVisible(true);
        Em5.continuar();
        }
        
        if("30".equals(EmpaCont.getText().toString())){
        Em5.pausa();
        }
    
        if(s.equals(Tproduccion.getText().toString())){

        Sa1.setVisible(true);
        Sa1.continuar();
        }
        
        
         
    if("6".equals(SalidaCont.getText().toString())){
        Sa1.pausa();
        Sa2.setVisible(true);
        Sa2.continuar();
        }
        
        if("12".equals(SalidaCont.getText().toString())){
        Sa2.pausa();
        Sa3.setVisible(true);
        Sa3.continuar();
        }
        
        if("18".equals(SalidaCont.getText().toString())){
        Sa3.pausa();
        Sa4.setVisible(true);
        Sa4.continuar();
        }
        
        if("24".equals(SalidaCont.getText().toString())){
        Sa4.pausa();
        Sa5.setVisible(true);
        Sa5.continuar();
        }
        
        if("30".equals(SalidaCont.getText().toString())){
        Sa5.pausa();
        }
        
        }
        
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new simulacion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private practica2.Circulo Em1;
    private practica2.Circulo Em2;
    private practica2.Circulo Em3;
    private practica2.Circulo Em4;
    private practica2.Circulo Em5;
    private javax.swing.JLabel EmpaCont;
    private javax.swing.JButton Inicio;
    private practica2.Circulo Inv1;
    private practica2.Circulo Inv2;
    private practica2.Circulo Inv3;
    private practica2.Circulo Inv4;
    private practica2.Circulo Inv5;
    private javax.swing.JLabel InventarioCont;
    private practica2.Circulo Pro1;
    private practica2.Circulo Pro2;
    private practica2.Circulo Pro3;
    private practica2.Circulo Pro4;
    private practica2.Circulo Pro5;
    private javax.swing.JLabel ProduccionCont;
    private practica2.Circulo Sa1;
    private practica2.Circulo Sa2;
    private practica2.Circulo Sa3;
    private practica2.Circulo Sa4;
    private practica2.Circulo Sa5;
    private javax.swing.JLabel SalidaCont;
    private javax.swing.JLabel Tempaquetado;
    private javax.swing.JLabel Tinventario;
    private javax.swing.JLabel Tproduccion;
    private javax.swing.JLabel Tsalida;
    private java.awt.Canvas canvas1;
    private practica2.Circulo finsalida;
    private practica2.Circulo inicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private practica2.mov mov2;
    private practica2.mov3 mov3;
    private practica2.mov4 mov4;
    private javax.swing.JLabel tiem;
    // End of variables declaration//GEN-END:variables
}
